import { UnitScenario } from './types';

export const INITIAL_SCENARIOS: Record<string, UnitScenario> = {
  'UNIT-0002': {
    unit_id: 'UNIT-0002',
    record_id: 'PRP-0002',
    org_id: 'org_demo_alpha',
    product_title: 'Hand-Poured Soy Lavender Candle (8oz)',
    category: 'Home & Candles · Fragile Glassware',
    sku: 'SKU-CANDLE-3',
    asin: 'B08ABC99XY',
    fnsku: 'X00DUMMY002',
    work_order_id: 'WO-3080',
    target_destination: 'Amazon FBA (ONT8)',
    fba_shipment_id: 'FBA-ONT8-3080',
    prep_price_usd: 0.40,
    chargeback_risk_usd: 2.00,
    packaging_spec: 'Bubble cushion + Fragile Label + Flat FNSKU',
    overall: 'PASS',
    evidence_sha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    photo_refs: [
      '/candle_stage.jpg',
      '/candle_stage.jpg',
      '/candle_stage.jpg'
    ],
    checks: [
      {
        id: 'polybag',
        code: 'FBA-POLY-101',
        ruleNumber: 'Rule 101',
        name: 'Polybag Sealed',
        badgeText: 'N/A',
        state: 'na',
        rawStatus: 'not_required',
        desc: 'Not applicable — Item is housed in corrugated individual carton.',
        rule: 'Amazon Seller Central: Polybagging mandatory for plush, apparel, or loose liquids.',
        confidence: 0.99,
        bbox: { top: '12%', left: '12%', width: '76%', height: '76%' },
        angleTarget: 'front'
      },
      {
        id: 'warning',
        code: 'FBA-WARN-201',
        ruleNumber: 'Rule 201',
        name: 'Suffocation Warning Label',
        badgeText: 'N/A',
        state: 'na',
        rawStatus: 'not_required',
        desc: 'Not applicable — Non-bagged rigid packaging container.',
        rule: 'Amazon Seller Central: Mandatory on bags with opening ≥ 5 inches.',
        confidence: 0.99,
        bbox: { top: '65%', left: '20%', width: '60%', height: '18%' },
        angleTarget: 'front'
      },
      {
        id: 'fnsku',
        code: 'FBA-FNSKU-301',
        ruleNumber: 'Rule 301',
        name: 'FNSKU Label Placement',
        badgeText: '98% Match',
        state: 'pass',
        rawStatus: 'flat',
        desc: 'Thermal label placed flat on smooth surface with 0.25in margins clear.',
        rule: 'Amazon Seller Central: Must be flat on the widest face; never on curve or seam.',
        confidence: 0.98,
        bbox: { top: '32%', left: '30%', width: '40%', height: '36%' },
        angleTarget: 'label'
      },
      {
        id: 'barcode',
        code: 'FBA-BC-401',
        ruleNumber: 'Rule 401',
        name: 'Original Barcode Covered',
        badgeText: '100% Obscured',
        state: 'pass',
        rawStatus: 'yes',
        desc: 'Manufacturer UPC is fully covered; no competing barcodes visible.',
        rule: 'Amazon Seller Central: Original scannable barcodes must be completely covered.',
        confidence: 0.96,
        bbox: { top: '32%', left: '30%', width: '40%', height: '36%' },
        angleTarget: 'label'
      },
      {
        id: 'expiry',
        code: 'FBA-EXP-501',
        ruleNumber: 'Rule 501',
        name: 'Expiry Date Legible',
        badgeText: 'N/A',
        state: 'na',
        rawStatus: 'not_required',
        desc: 'Non-perishable candle inventory; expiration date not mandated.',
        rule: 'Amazon Seller Central: Food, vitamins, and topicals must show expiry date.',
        confidence: 0.99,
        bbox: { top: '72%', left: '68%', width: '22%', height: '16%' },
        angleTarget: 'front'
      },
      {
        id: 'handling',
        code: 'FBA-HNDL-601',
        ruleNumber: 'Rule 601',
        name: 'Fragile / Glass Warning Mark',
        badgeText: 'Verified',
        state: 'pass',
        rawStatus: 'all_present',
        desc: 'Fragile packaging requirement fulfilled with outer warning label verified.',
        rule: 'Amazon Seller Central: Glass and ceramic commodities require prominent fragile mark.',
        confidence: 0.95,
        bbox: { top: '14%', left: '16%', width: '28%', height: '24%' },
        angleTarget: 'front'
      }
    ]
  },

  'UNIT-0003': {
    unit_id: 'UNIT-0003',
    record_id: 'PRP-0003',
    org_id: 'org_demo_bravo',
    product_title: '1,000-Piece National Parks Panoramic Puzzle Box',
    category: 'Toys & Games · Card Games & Puzzles',
    sku: 'SKU-PUZZLE-500',
    asin: 'B0DUMMY729',
    fnsku: 'X00DUMMY003',
    work_order_id: 'WO-3079',
    target_destination: 'Amazon FBA (CLT2)',
    fba_shipment_id: 'FBA-CLT2-3079',
    prep_price_usd: 0.90,
    chargeback_risk_usd: 2.00,
    packaging_spec: 'Polybag Enclosure (≥5" opening) + Suffocation Warning + FNSKU',
    overall: 'FAIL',
    defect_title: 'Unsealed Polybag Seam (4.2cm Gap)',
    defect_remediation: 'Return unit to impulse sealer. Re-seal top continuous edge before boxing.',
    evidence_sha256: '7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
    photo_refs: [
      '/puzzle_stage.jpg',
      '/puzzle_stage.jpg',
      '/puzzle_stage.jpg'
    ],
    checks: [
      {
        id: 'polybag',
        code: 'FBA-POLY-101',
        ruleNumber: 'Rule 101',
        name: 'Polybag Sealed',
        badgeText: 'FAILED',
        state: 'fail',
        rawStatus: 'not_sealed',
        desc: 'DEFECT: Polybag top opening has a 4.2cm unsealed gap. FBA mandates hermetic heat seal.',
        rule: 'Amazon Seller Central: Polybags must be completely heat-sealed or taped securely.',
        confidence: 0.97,
        bbox: { top: '6%', left: '10%', width: '80%', height: '22%' },
        angleTarget: 'seam'
      },
      {
        id: 'warning',
        code: 'FBA-WARN-201',
        ruleNumber: 'Rule 201',
        name: 'Suffocation Warning Label',
        badgeText: 'Verified',
        state: 'pass',
        rawStatus: 'legible',
        desc: 'Printed suffocation warning verified in compliant font size (≥14pt) on polybag.',
        rule: 'Amazon Seller Central: Mandatory warning for bags with opening ≥ 5 inches.',
        confidence: 0.94,
        bbox: { top: '68%', left: '18%', width: '64%', height: '18%' },
        angleTarget: 'front'
      },
      {
        id: 'fnsku',
        code: 'FBA-FNSKU-301',
        ruleNumber: 'Rule 301',
        name: 'FNSKU Label Placement',
        badgeText: '99% Match',
        state: 'pass',
        rawStatus: 'flat',
        desc: 'FNSKU barcode applied flat with unobstructed quiet scanning zone.',
        rule: 'Amazon Seller Central: Must be placed flat on the widest face.',
        confidence: 0.97,
        bbox: { top: '34%', left: '32%', width: '36%', height: '32%' },
        angleTarget: 'label'
      },
      {
        id: 'barcode',
        code: 'FBA-BC-401',
        ruleNumber: 'Rule 401',
        name: 'Original Barcode Covered',
        badgeText: '100% Obscured',
        state: 'pass',
        rawStatus: 'yes',
        desc: 'Box UPC is completely defaced and covered under opaque thermal label.',
        rule: 'Amazon Seller Central: Original barcodes must be covered.',
        confidence: 0.95,
        bbox: { top: '34%', left: '32%', width: '36%', height: '32%' },
        angleTarget: 'label'
      },
      {
        id: 'expiry',
        code: 'FBA-EXP-501',
        ruleNumber: 'Rule 501',
        name: 'Expiry Date Legible',
        badgeText: 'N/A',
        state: 'na',
        rawStatus: 'not_required',
        desc: 'Board game is non-perishable; expiry date verification not required.',
        rule: 'Amazon Seller Central: Perishables only.',
        confidence: 0.99,
        bbox: { top: '72%', left: '68%', width: '22%', height: '16%' },
        angleTarget: 'front'
      },
      {
        id: 'handling',
        code: 'FBA-HNDL-601',
        ruleNumber: 'Rule 601',
        name: 'Fragile / Glass Warning Mark',
        badgeText: 'N/A',
        state: 'na',
        rawStatus: 'not_required',
        desc: 'Standard non-fragile commodity.',
        rule: 'Amazon Seller Central: Fragile or liquid commodities only.',
        confidence: 0.99,
        bbox: { top: '14%', left: '14%', width: '26%', height: '26%' },
        angleTarget: 'front'
      }
    ]
  },

  'UNIT-0004': {
    unit_id: 'UNIT-0004',
    record_id: 'PRP-0004',
    org_id: 'org_demo_alpha',
    product_title: 'Vanilla Whey Isolate Protein Tub (2.2 lbs)',
    category: 'Grocery & Dietary Supplements · Sports Nutrition',
    sku: 'SKU-PROT-1KG',
    asin: 'B0DUMMY357',
    fnsku: 'X00DUMMY004',
    work_order_id: 'WO-3081',
    target_destination: 'Amazon FBA (MDW2)',
    fba_shipment_id: 'FBA-MDW2-3081',
    prep_price_usd: 1.10,
    chargeback_risk_usd: 2.00,
    packaging_spec: 'Tamper seal intact + Expiry date visible + 100% UPC Cover',
    overall: 'FAIL',
    defect_title: 'Manufacturer UPC Barcode Fully Exposed',
    defect_remediation: 'Place blank thermal label over UPC or re-center FNSKU directly over it.',
    evidence_sha256: '4e07408562bedb8b60ce05c1decfe3ad16b72230967de01f640b7e4729b49fce',
    photo_refs: [
      '/protein_stage.jpg',
      '/protein_stage.jpg',
      '/protein_stage.jpg'
    ],
    checks: [
      {
        id: 'polybag',
        code: 'FBA-POLY-101',
        ruleNumber: 'Rule 101',
        name: 'Polybag Sealed',
        badgeText: 'N/A',
        state: 'na',
        rawStatus: 'not_required',
        desc: 'Rigid plastic canister container does not require secondary polybagging.',
        rule: 'Amazon Seller Central: Rigid containers do not require bagging.',
        confidence: 0.99,
        bbox: { top: '10%', left: '10%', width: '80%', height: '80%' },
        angleTarget: 'front'
      },
      {
        id: 'warning',
        code: 'FBA-WARN-201',
        ruleNumber: 'Rule 201',
        name: 'Suffocation Warning Label',
        badgeText: 'N/A',
        state: 'na',
        rawStatus: 'not_required',
        desc: 'Not applicable to rigid tubs.',
        rule: 'Amazon Seller Central: Polybags only.',
        confidence: 0.99,
        bbox: { top: '68%', left: '18%', width: '64%', height: '18%' },
        angleTarget: 'front'
      },
      {
        id: 'fnsku',
        code: 'FBA-FNSKU-301',
        ruleNumber: 'Rule 301',
        name: 'FNSKU Label Placement',
        badgeText: '99% Match',
        state: 'pass',
        rawStatus: 'flat',
        desc: 'FNSKU barcode is applied flat on container sidewall.',
        rule: 'Amazon Seller Central: Flat surface placement required.',
        confidence: 0.96,
        bbox: { top: '30%', left: '20%', width: '32%', height: '36%' },
        angleTarget: 'label'
      },
      {
        id: 'barcode',
        code: 'FBA-BC-401',
        ruleNumber: 'Rule 401',
        name: 'Original Barcode Covered',
        badgeText: 'FAILED',
        state: 'fail',
        rawStatus: 'no',
        desc: 'DEFECT: Manufacturer UPC is fully exposed adjacent to FNSKU. High FC mis-scan risk.',
        rule: 'Amazon Seller Central: Original barcodes must be covered to prevent mis-scans.',
        confidence: 0.98,
        bbox: { top: '30%', left: '56%', width: '30%', height: '36%' },
        angleTarget: 'label'
      },
      {
        id: 'expiry',
        code: 'FBA-EXP-501',
        ruleNumber: 'Rule 501',
        name: 'Expiry Date Legible',
        badgeText: 'Verified',
        state: 'pass',
        rawStatus: 'legible',
        desc: 'Expiration date (EXP 11/2027) verified on container shoulder.',
        rule: 'Amazon Seller Central: Consumables must display legible expiration date.',
        confidence: 0.95,
        bbox: { top: '14%', left: '54%', width: '32%', height: '16%' },
        angleTarget: 'front'
      },
      {
        id: 'handling',
        code: 'FBA-HNDL-601',
        ruleNumber: 'Rule 601',
        name: 'Fragile / Glass Warning Mark',
        badgeText: 'N/A',
        state: 'na',
        rawStatus: 'not_required',
        desc: 'Not required for dry powder container.',
        rule: 'Amazon Seller Central: Fragile or liquid commodities only.',
        confidence: 0.99,
        bbox: { top: '14%', left: '14%', width: '26%', height: '26%' },
        angleTarget: 'front'
      }
    ]
  },

  'UNIT-0010': {
    unit_id: 'UNIT-0010',
    record_id: 'PRP-0010',
    org_id: 'org_demo_alpha',
    product_title: 'Nordic Minimalist Ceramic Desk Lamp',
    sku: 'SKU-LAMP-LED',
    asin: 'B0DUMMY357',
    fnsku: 'X00DUMMY010',
    work_order_id: 'WO-3000',
    fba_shipment_id: 'FBA-DUMMY-100',
    prep_price_usd: 0.75,
    chargeback_risk_usd: 2.00,
    packaging_spec: 'Drop-tested carton + Fragile label + Flat FNSKU',
    overall: 'FAIL',
    defect_title: 'FNSKU Wrapped Around 90° Box Corner',
    defect_remediation: 'Peel and remount FNSKU flat on the widest face with >0.25in border margin.',
    evidence_sha256: '2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae',
    photo_refs: [
      'fixtures/prep/UNIT-0010_front.jpg',
      'fixtures/prep/UNIT-0010_back.jpg',
      'fixtures/prep/UNIT-0010_label.jpg'
    ],
    checks: [
      {
        id: 'polybag',
        code: 'FBA-POLY-101',
        name: 'Polybag Sealed',
        state: 'na',
        rawStatus: 'not_required',
        desc: 'Rigid carton; bagging not required.',
        rule: 'Amazon Seller Central: Rigid boxes exempt.',
        confidence: 0.99,
        bbox: { top: '10%', left: '10%', width: '80%', height: '80%' },
        angleTarget: 'front'
      },
      {
        id: 'warning',
        code: 'FBA-WARN-201',
        name: 'Suffocation Warning',
        state: 'na',
        rawStatus: 'not_required',
        desc: 'Not required for corrugated box.',
        rule: 'Amazon Seller Central: Polybags only.',
        confidence: 0.99,
        bbox: { top: '68%', left: '18%', width: '64%', height: '18%' },
        angleTarget: 'front'
      },
      {
        id: 'fnsku',
        code: 'FBA-FNSKU-301',
        name: 'FNSKU Label Placement',
        state: 'fail',
        rawStatus: 'on_edge',
        desc: 'DEFECT: Barcode is folded across 90° box corner seam. Unscannable by Amazon automated sorters.',
        rule: 'Amazon Seller Central: Never wrap barcode label over an edge or seam.',
        confidence: 0.97,
        bbox: { top: '24%', left: '72%', width: '22%', height: '52%' },
        angleTarget: 'label'
      },
      {
        id: 'barcode',
        code: 'FBA-BC-401',
        name: 'Original Barcode Covered',
        state: 'pass',
        rawStatus: 'yes',
        desc: 'Original manufacturer UPC covered.',
        rule: 'Amazon Seller Central: Original barcodes must be covered.',
        confidence: 0.95,
        bbox: { top: '34%', left: '32%', width: '36%', height: '32%' },
        angleTarget: 'label'
      },
      {
        id: 'expiry',
        code: 'FBA-EXP-501',
        name: 'Expiry Date Visibility',
        state: 'na',
        rawStatus: 'not_required',
        desc: 'Non-perishable hardware.',
        rule: 'Amazon Seller Central: Perishables only.',
        confidence: 0.99,
        bbox: { top: '72%', left: '68%', width: '22%', height: '16%' },
        angleTarget: 'front'
      },
      {
        id: 'handling',
        code: 'FBA-HNDL-601',
        name: 'Handling / Fragile Marks',
        state: 'pass',
        rawStatus: 'all_present',
        desc: 'Fragile handling sticker verified on primary display panel.',
        rule: 'Amazon Seller Central: Ceramic items require fragile mark.',
        confidence: 0.96,
        bbox: { top: '16%', left: '16%', width: '26%', height: '24%' },
        angleTarget: 'front'
      }
    ]
  },

  'UNIT-0012': {
    unit_id: 'UNIT-0012',
    record_id: 'PRP-0012',
    org_id: 'org_demo_alpha',
    product_title: 'Handmade Stoneware Ceramic Coffee Mug',
    sku: 'SKU-MUG-CERAMIC',
    asin: 'B0DUMMY890',
    fnsku: 'X00DUMMY012',
    work_order_id: 'WO-3000',
    fba_shipment_id: 'FBA-DUMMY-100',
    prep_price_usd: 0.50,
    chargeback_risk_usd: 2.00,
    packaging_spec: 'Polybag + Suffocation Warning + Fragile Cushioning',
    overall: 'UNCERTAIN',
    defect_title: 'Specular Glare Obscuring Suffocation Warning Text',
    defect_remediation: 'Tilt package 15° away from overhead light rig and press [Space] to retake.',
    evidence_sha256: 'fcde2b2edba56bf408601fb721fe9b5c338d10ee429ea04fae5511b68fbf8fb9',
    photo_refs: [
      'fixtures/prep/UNIT-0012_front.jpg',
      'fixtures/prep/UNIT-0012_back.jpg',
      'fixtures/prep/UNIT-0012_label.jpg'
    ],
    checks: [
      {
        id: 'polybag',
        code: 'FBA-POLY-101',
        name: 'Polybag Sealed',
        state: 'pass',
        rawStatus: 'yes',
        desc: 'Unit is securely sealed in protective 1.5mil polybag.',
        rule: 'Amazon Seller Central: Bag must be sealed securely.',
        confidence: 0.95,
        bbox: { top: '10%', left: '10%', width: '80%', height: '80%' },
        angleTarget: 'seam'
      },
      {
        id: 'warning',
        code: 'FBA-WARN-201',
        name: 'Suffocation Warning',
        state: 'uncertain',
        rawStatus: 'uncertain',
        desc: 'UNCERTAIN: Specular reflection over polybag surface conceals font size legibility.',
        rule: 'Amazon Seller Central: Warning text must be clearly legible and ≥14pt font.',
        confidence: 0.58,
        bbox: { top: '55%', left: '20%', width: '60%', height: '25%' },
        angleTarget: 'front'
      },
      {
        id: 'fnsku',
        code: 'FBA-FNSKU-301',
        name: 'FNSKU Label Placement',
        state: 'pass',
        rawStatus: 'flat',
        desc: 'FNSKU label flat on exterior polybag face.',
        rule: 'Amazon Seller Central: Flat surface placement required.',
        confidence: 0.96,
        bbox: { top: '34%', left: '32%', width: '36%', height: '32%' },
        angleTarget: 'label'
      },
      {
        id: 'barcode',
        code: 'FBA-BC-401',
        name: 'Original Barcode Covered',
        state: 'pass',
        rawStatus: 'yes',
        desc: 'No conflicting barcodes exposed.',
        rule: 'Amazon Seller Central: Original barcodes must be covered.',
        confidence: 0.96,
        bbox: { top: '34%', left: '32%', width: '36%', height: '32%' },
        angleTarget: 'label'
      },
      {
        id: 'expiry',
        code: 'FBA-EXP-501',
        name: 'Expiry Date Visibility',
        state: 'na',
        rawStatus: 'not_required',
        desc: 'Ceramic mug non-perishable.',
        rule: 'Amazon Seller Central: Perishables only.',
        confidence: 0.99,
        bbox: { top: '72%', left: '68%', width: '22%', height: '16%' },
        angleTarget: 'front'
      },
      {
        id: 'handling',
        code: 'FBA-HNDL-601',
        name: 'Handling / Fragile Marks',
        state: 'pass',
        rawStatus: 'all_present',
        desc: 'Fragile label affixed to front face.',
        rule: 'Amazon Seller Central: Ceramic items require fragile mark.',
        confidence: 0.97,
        bbox: { top: '16%', left: '16%', width: '26%', height: '24%' },
        angleTarget: 'front'
      }
    ]
  }
};

export const MOCK_WORK_ORDERS = [
  {
    work_order_id: 'WO-3000',
    client_name: 'Apex Brand Partners',
    fba_shipment_id: 'FBA-18X9A2Z',
    destination_fc: 'CLT2 · Charlotte, NC',
    total_units: 450,
    passed_units: 438,
    rework_units: 12,
    disputed_units: 0,
    prep_fee_rate: 0.90,
    total_revenue_usd: 405.00,
    status: 'in_progress' as const,
  },
  {
    work_order_id: 'WO-2998',
    client_name: 'National Puzzles Co.',
    fba_shipment_id: 'FBA-DUMMY-100',
    destination_fc: 'RDU2 · Raleigh, NC',
    total_units: 120,
    passed_units: 110,
    rework_units: 10,
    disputed_units: 10,
    prep_fee_rate: 0.75,
    total_revenue_usd: 90.00,
    status: 'audited' as const,
  },
  {
    work_order_id: 'WO-2995',
    client_name: 'Pure Nutrition Labs',
    fba_shipment_id: 'FBA-15K99B2',
    destination_fc: 'ONT8 · Moreno Valley, CA',
    total_units: 600,
    passed_units: 588,
    rework_units: 12,
    disputed_units: 24,
    prep_fee_rate: 1.10,
    total_revenue_usd: 660.00,
    status: 'dispatched' as const,
  },
];

export const MOCK_DISPUTES = [
  {
    dispute_id: 'DISP-2026-0914',
    fba_shipment_id: 'FBA-DUMMY-100',
    fc_destination: 'CLT2 (Charlotte FC)',
    sku: 'SKU-PUZZLE-500',
    fnsku: 'X00DUMMY003',
    claimed_defect: 'Missing Suffocation Warning ($2.00/unit fee)',
    fee_per_unit_usd: 2.00,
    claimed_units: 10,
    total_chargeback_usd: 20.00,
    notice_date: '2026-09-28 (6 Weeks Post-Dispatch)',
    matching_record_id: 'PRP-0003',
    our_evidence_summary: 'Overhead 4K camera Angle 1 proves 16pt bold warning was heat-stamped directly on polybag with 0.25in clearance. FC receiving laser mis-scan.',
    dispute_status: 'pending' as const,
  },
  {
    dispute_id: 'DISP-2026-0881',
    fba_shipment_id: 'FBA-15K99B2',
    fc_destination: 'ONT8 (Moreno Valley)',
    sku: 'SKU-CANDLE-3',
    fnsku: 'X00DUMMY002',
    claimed_defect: 'Unplanned Bubble Wrap & Fragile Prep Required',
    fee_per_unit_usd: 1.50,
    claimed_units: 24,
    total_chargeback_usd: 36.00,
    notice_date: '2026-09-12',
    matching_record_id: 'PRP-0002',
    our_evidence_summary: 'Overhead 4K angles 1 & 2 confirm 3/16 inch bubble wrap enclosure and high-visibility Fragile label. Rebuttal accepted by Amazon Seller Support.',
    dispute_status: 'recovered' as const,
  },
];

export const MOCK_VAULT_RECORDS = [
  {
    record_id: 'PRP-0002',
    unit_id: 'UNIT-0002',
    work_order: 'WO-3000',
    sku: 'SKU-CANDLE-3',
    fnsku: 'X00DUMMY002',
    verdict: 'PASS',
    prep_fee: 0.40,
    operator: 'op_amira',
    captured_at: '2026-10-01 10:14 UTC',
    rule_status: 'All 6 Verified',
  },
  {
    record_id: 'PRP-0003',
    unit_id: 'UNIT-0003',
    work_order: 'WO-3000',
    sku: 'SKU-PUZZLE-500',
    fnsku: 'X00DUMMY003',
    verdict: 'FAIL',
    prep_fee: 0.90,
    operator: 'op_amira',
    captured_at: '2026-10-01 10:18 UTC',
    rule_status: 'FBA-POLY-101 Defect (Unsealed)',
  },
  {
    record_id: 'PRP-0004',
    unit_id: 'UNIT-0004',
    work_order: 'WO-3000',
    sku: 'SKU-PROT-1KG',
    fnsku: 'X00DUMMY004',
    verdict: 'FAIL',
    prep_fee: 1.10,
    operator: 'op_fatima',
    captured_at: '2026-10-01 10:22 UTC',
    rule_status: 'FBA-BC-401 Defect (Exposed UPC)',
  },
  {
    record_id: 'PRP-0010',
    unit_id: 'UNIT-0010',
    work_order: 'WO-2998',
    sku: 'SKU-LAMP-LED',
    fnsku: 'X00DUMMY010',
    verdict: 'FAIL',
    prep_fee: 0.75,
    operator: 'op_amira',
    captured_at: '2026-10-01 10:25 UTC',
    rule_status: 'FBA-FNSKU-301 Defect (On Seam)',
  },
  {
    record_id: 'PRP-0012',
    unit_id: 'UNIT-0012',
    work_order: 'WO-2998',
    sku: 'SKU-MUG-CERAMIC',
    fnsku: 'X00DUMMY012',
    verdict: 'UNCERTAIN',
    prep_fee: 0.50,
    operator: 'op_fatima',
    captured_at: '2026-10-01 10:29 UTC',
    rule_status: 'FBA-WARN-201 Glare Review',
  },
];

